---
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17 # Get the latest version from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terraform-validate
    - id: terraform-fmt
    # TODO: Add this hook in Part Deux.
    # - id: tflint
    #   args:
    #     - "--module"
    #     - "--deep"
    #     - "--config=.tflint.hcl"
# TODO: Add these hooks in Part Trois.
# - repo: git://github.com/antonbabenko/pre-commit-terraform
#   rev: <VERSION> # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
#   hooks:
#     - id: terraform_tfsec
#     - id: terraform_docs
#     - id: checkov

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0 # Get the latest version from: https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: check-merge-conflict
